### Validation token
GET http://localhost:8080/valid_code/bob
Accept: application/json


> {%
    client.test("Valid promo code should return 200", function() {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body.code === "bob", "Code should be 'bob'");
        client.assert(response.body.valid === true, "valid should be 'true'");
    });
%}
