### 1. Получение токена
POST http://localhost:8080/login
Content-Type: application/json

{
  "login": "admin",
  "password": "secret"
}

> {%
    // Сохраняем токен в переменную, чтобы использовать в следующем запросе
    var body = response.body;
    var data = JSON.parse(body);
    client.global.set("authToken", data.token);  // предполагаем, что сервер вернул { "token": "..." }
%}


### 3. Защищённый запрос с токеном
GET http://localhost:8080/secure/valid_code/bob1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlcyI6WyJhZG1pbiJdLCJzdWIiOiIxMjMiLCJhdWQiOlsiIl0sImV4cCI6MTc1NjI3MDU1Mn0.VfTdMBbeB0yOxXju6tqLgKW6AQESkjflB1VpavcEZ7U

> {%
    client.test("Protected endpoint returns 200", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}